version: '3.8'
services:
  # Bitcoin-core for development
  bitcoin-core:
    build:
      context: ./docker/bitcoin-core
      dockerfile: ./Dockerfile
    ports:
      - 18443:18443
      - 18444:18444
    volumes:
      - ./docker/bitcoin-core/data:/home/bitcoin/.bitcoin

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379
