# 🟠 This is example docker-compose.yml file for running bamotf/server in development mode.

version: '3.8'
services:
  bamotf:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: bamotf
    restart: always
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://johndoe:randompassword@postgres:5432
      - BITCOIN_CORE_URL=http://username:wc7eFmVwEeZCDYTMaOqxRnLWSR7aI76bGmHl6pRFtAU@bitcoin-core:18443
      - WEBHOOK_URL=http://localhost:4000
      - WEBHOOK_SECRET=my-secret
      - API_KEY=<preferable-a-very-long-api-key>
    ports:
      - 21000:21000
    depends_on:
      - postgres
      - redis
      - bitcoin-core

  # Bitcoin-core for development
  bitcoin-core:
    extends:
      file: ./docker-compose.yml
      service: bitcoin-core

  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres
    healthcheck:
      test: ['CMD', 'pg_isready']

  redis:
    extends:
      file: ./docker-compose.yml
      service: redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
