# 🟠 This is example docker-compose.yml file for running bamotf/server in development mode.

version: '3.8'
services:
  bamotf:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: bamotf
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgresql://johndoe:randompassword@postgres:5432
      - DEV_MODE_ENABLED=true
      - DEV_API_KEY=my-key
      - DEV_WEBHOOK_URL=http://localhost:3001/webhook
      - DEV_WEBHOOK_SECRET=my-secret
    ports:
      - 21000:21000
    depends_on:
      - postgres
      - redis
      - bitcoin-core

  # Bitcoin-core for development
  bitcoin-core:
    extends:
      file: ./docker-compose.yml
      service: bitcoin-core

  postgres:
    extends:
      file: ./docker-compose.yml
      service: postgres
    healthcheck:
      test: ['CMD', 'pg_isready']

  redis:
    extends:
      file: ./docker-compose.yml
      service: redis
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
