version: '3.8'
services:
  bitcoin-core:
    image: btcpayserver/bitcoin:24.0.1 # doesn't have a latest tag 😕
    environment:
      - BITCOIN_NETWORK=regtest
      - |
        BITCOIN_EXTRA_ARGS=
        rpcuser=username
        rpcpassword=password
        rpcbind=0.0.0.0
        debug=http
        rpcallowip=0.0.0.0/0
      # fallbackfee=0.00001
      # server=1
      # rpcport=8332
    ports:
      - '8332:8332' # RPC
      - '8333:8333' # bitcoin clients
      # - "8334:8334" # Tor connections
      - '18443:18443' # ???
      - '18444:18444' # ???
      # - "18445:18445" # ???
    volumes:
      - ./docker/server/data:/data

  quirrel:
    image: ghcr.io/quirrel-dev/quirrel:sha-855909d

  # cashier:
  #   build:
  #     context: .
  #     dockerfile: ./docker/server/Dockerfile
  #   environment:
  #     - API_KEY
  #   ports:
  #     - "2345:2345"
# depends_on:
#       - db
