# 🟠 This is example docker-compose.yml file for running bam-otf-server in development mode.

version: '3.8'
services:
  bam-otf-server:
    container_name: bam-otf-server
    restart: always
    build:
      context: ../..
      dockerfile: ./apps/bam-otf-server/Dockerfile
    environment:
      - REDIS_URL=redis://redis:26379
      - POSTGRES_URL=postgresql://johndoe:randompassword@postgres:25432
      - BITCOIN_CORE_URL=http://username:wc7eFmVwEeZCDYTMaOqxRnLWSR7aI76bGmHl6pRFtAU@bitcoin-core:18443
      - WEBHOOK_URL=http://localhost:4000
      - WEBHOOK_SECRET=my-secret
    ports:
      - 42000:3000
    depends_on:
      - postgres
      - redis
      - bitcoin-core

  # Bitcoin-core for development
  bitcoin-core:
    build:
      context: ../../docker/bitcoin-core
      dockerfile: ./Dockerfile
    ports:
      - 18443:18443
      - 18444:18444
    volumes:
      - ./bitcoin-core:/home/bitcoin/.bitcoin

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    ports:
      - '25432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '26379:6379'
